name: letsgt
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  amplify_api: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_flutter: ^1.0.0
  auto_route: ^7.1.0
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  geolocator: ^9.0.2
  image_picker: ^0.8.7+3
  permission_handler: ^10.2.0
  riverpod: ^2.3.5

dev_dependencies:
  auto_route_generator: ^7.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

