name: Analyze code
on:
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    if: ${{ !contains(github.triggering_actor, '[bot]') }}
    name: PR Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PAT }}
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: dart format .
      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v2
      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit change & Push
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "CI AUTO Format"
          git push
